### ISSUE TITLE
1MB limit on Cloudflare Workers Free Plan with resvg.wasm

### ISSUE THREAD

**Issue by paramaggarwal** [kvnang/workers-og#7]
Hi, From what I understand the purpose of the library was the fix the size issue (https://github.com/kvnang/workers-og/commit/9e3ff8459a5c86baeec5cc3649081d401155974d) of the resvg.wasm file to be at 1.31MB.

I wanted to bring to your notice that the upstream version is also updated now: https://github.com/vercel/next.js/pull/60205

Also, I am running into the 1MB size limit on Cloudflare Workers Free Plan - any suggestions about this?

**Comment by kvnang** [comment]
Hi @paramaggarwal Since version `0.0.19`, this package should be using the same `resvg-wasm` version (not the newest one, which is significantly larger) as the one on Vercel's. For me, it results in ~720KiB (gzip) for a simple application. Let me know if you still run into any issue, and if so, could you please detail what your app looks like? Thanks for raising the issue.

**Comment by imjlk** [comment]
Hi,
I understand the need to use a lower version on the Workers Free plan, but are there any ways to add the latest resvg-wasm(>= 2.6.0) module version for paid users?

A simple way to think about it is to leave workers-og at 2.4.0 and add other packages to reflect the new updates.

I think we'll need to go in this direction in the future if we want to [support webp](https://github.com/RazrFalcon/resvg/blob/master/CHANGELOG.md#0430---2024-08-10), what do you think?

**Comment by paramaggarwal** [comment]
We can have two versions of resvg: `resvg-lite` ands `resvg`
